### ISSUE TITLE
oS Leap 15.2: podman: podman: symbol lookup error: /usr/lib64/libgobject-2.0.so.0

### ISSUE THREAD

**Issue by sebastian-philipp** [SUSE/ceph-bootstrap#67]
via `sesdev octopus`

```
node1:/var/log/ceph # cat /etc/os-release
NAME="openSUSE Leap"
VERSION="15.2 Alpha"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.2"
PRETTY_NAME="openSUSE Leap 15.2 Alpha"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
node1:/var/log/ceph # cat cephadm.log 
INFO:root:Cluster fsid: e4da5eea-48e5-11ea-ac19-52540035718e
DEBUG:cephadm:Acquiring lock 139682512336824 on /run/cephadm/e4da5eea-48e5-11ea-ac19-52540035718e.lock
DEBUG:cephadm:Lock 139682512336824 acquired on /run/cephadm/e4da5eea-48e5-11ea-ac19-52540035718e.lock
INFO:cephadm:Verifying IP 10.20.57.201 port 3300 ...
INFO:cephadm:Verifying IP 10.20.57.201 port 6789 ...
DEBUG:cephadm:Final addrv is [v2:10.20.57.201:3300,v1:10.20.57.201:6789]
INFO:cephadm:Pulling latest ceph/daemon-base:latest-master-devel container...
DEBUG:cephadm:Running command: /usr/bin/podman pull ceph/daemon-base:latest-master-devel
DEBUG:cephadm:/usr/bin/podman:stderr /usr/bin/podman: symbol lookup error: /usr/lib64/libgobject-2.0.so.0: undefined symbol: g_date_copy
INFO:cephadm:Non-zero exit code 127 from /usr/bin/podman pull ceph/daemon-base:latest-master-devel
INFO:cephadm:/usr/bin/podman:stderr /usr/bin/podman: symbol lookup error: /usr/lib64/libgobject-2.0.so.0: undefined symbol: g_date_copy
Traceback (most recent call last):
  File "/usr/sbin/cephadm", line 2811, in <module>
    r = args.func()
  File "/usr/sbin/cephadm", line 1654, in command_bootstrap
    call_throws([container_path, 'pull', args.image])
  File "/usr/sbin/cephadm", line 491, in call_throws
    raise RuntimeError('Failed command: %s' % ' '.join(command))
RuntimeError: Failed command: /usr/bin/podman pull ceph/daemon-base:latest-master-devel
DEBUG:cephadm:Releasing lock 139682512336824 on /run/cephadm/e4da5eea-48e5-11ea-ac19-52540035718e.lock
DEBUG:cephadm:Lock 139682512336824 released on /run/cephadm/e4da5eea-48e5-11ea-ac19-52540035718e.lock
node1:/var/log/ceph # zypper if podman
Loading repository data...
Reading installed packages...


Information for package podman:
-------------------------------
Repository     : Main Repository                                                      
Name           : podman                                                               
Version        : 1.4.4-lp152.2.10                                                     
Arch           : x86_64                                                               
Vendor         : openSUSE                                                             
Installed Size : 103.2 MiB                                                            
Installed      : Yes (automatically)                                                  
Status         : up-to-date                                                           
Source package : podman-1.4.4-lp152.2.10.src                                          
Summary        : Daemon-less container engine for managing containers, pods and images
Description    :                                                                      
    Podman is a container engine for managing pods, containers, and container
    images.
    It is a standalone tool and it directly manipulates containers without the need
    of a container engine daemon.
    Podman is able to interact with container images create in buildah, cri-o, and
    skopeo, as they all share the same datastore backend.

node1:/var/log/ceph # zypper if libgobject-2_0-0
Loading repository data...
Reading installed packages...


Information for package libgobject-2_0-0:
-----------------------------------------
Repository     : Main Repository                
Name           : libgobject-2_0-0               
Version        : 2.62.4-lp152.1.1               
Arch           : x86_64                         
Vendor         : openSUSE                       
Installed Size : 368.8 KiB                      
Installed      : Yes (automatically)            
Status         : up-to-date                     
Source package : glib2-2.62.4-lp152.1.1.src     
Summary        : Object-Oriented Framework for C
Description    :                                
    GLib is a general-purpose utility library, which provides many useful
    data types, macros, type conversions, string utilities, file utilities,
    a main loop abstraction, and so on.

    The GObject library provides an object-oriented framework for C.
```

My question is, where does it come from?
* podman dependencies? 
* problem with the Leap repositories?

**Comment by sebastian-philipp** [comment]
https://bugzilla.opensuse.org/show_bug.cgi?id=1163009
